QuanLyBanHang/QuanLyBanHang/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using QuanLyBanHang.Entity;
using QuanLyBanHang.Models.Cart;
using QuanLyBanHang.Models.Order;
using QuanLyBanHang.Models.Product;
using QuanLyBanHang.Service;

namespace QuanLyBanHang.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private IOrderService _orderService;
        private IOrderDetailService _orderDetailService;
        private ICartService _cartService;
        private IProductService _productService;
        private IWebHostEnvironment _webHostEnvironment;
        public CartController(IProductService productService,
            IOrderService orderService,
            IWebHostEnvironment webHostEnvironment,
            ICartService cartService,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IOrderDetailService orderDetailService)
        {
            _orderService = orderService;
            _productService = productService;
            _webHostEnvironment = webHostEnvironment;
            _cartService = cartService;
            _userManager = userManager;
            _signInManager = signInManager;
            _orderDetailService = orderDetailService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var username = _userManager.GetUserName(User);
            var model = _cartService.GetAll().Where(c => c.nameofUser == username).ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult AddToCart(int id)
        {
            var product = _productService.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            if(product.proStatus == Status.Unavailable)
            {
                TempData["ErrorMessage"] = "["+product.proName+"] is unavailable.";
                return RedirectToAction("Index","Shop");
            }
            var model = new CartAddViewModel
            {
                
                proID = product.proID,
                proName = product.proName,
                proSize = product.proSize,
                proPrice = product.proPrice,
                Producer = product.Producer,
                ImageUrl = product.ImageUrl,
                forGender = product.forGender,
                availableQuantity = product.Quantity
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddToCart([FromForm] CartAddViewModel model)
        {
            if (ModelState.IsValid)
            {
                var username = _userManager.GetUserName(User);                
                if (username == null)
                {
                    return NotFound();
                }
                var findCartItem = _cartService.GetAll().Where(c => c.proId == model.proID && c.nameofUser == username).FirstOrDefault();
                var temp = 0;
                if (findCartItem == null)
                {
                    temp = 0;
                }
                else
                    temp = findCartItem.Quantity;
                if (model.Quantity + temp <= model.availableQuantity)
                {
                    var cart = new Cart
                    {
                        proPrice = model.proPrice,
                        nameofUser = username,
                        proId = model.proID,
                        proName = model.proName,
                        proImage = model.ImageUrl,
                        Quantity = model.Quantity,
                        DateCreated = model.DateCreated,
                    };
                    await _cartService.AddItemToCart(cart);
                    return RedirectToAction("Index", "Shop");
                }
                else
                {
                    TempData["ErrorMessage"] = "Available quantity is: " + model.availableQuantity + ", please try again!";
                    return View(model);
                }
            }
            return View();

        }
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var product = _productService.GetById(id);
            if (product == null)
            {
                return NotFound();
            }
            var model = new ProductDetailViewModel
            {
                Id = product.proID,
                proName = product.proName,
                proSize = product.proSize,
                proPrice = product.proPrice,
                proDiscount = product.proDiscount,
                proUpdateDate = product.proUpdateDate,
                proDescription = product.proDescription,
                Producer = product.Producer,
                Quantity = product.Quantity,
                ImageUrl = product.ImageUrl,
                proStatus = product.proStatus,
                forGender = product.forGender
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult ReduceQuantity(int id)
        {
            var cart = _cartService.GetByProID(id);
            if (cart == null)
            {
                return NotFound();
            }
            var model = new CartDeleteViewModel
            {
                UserName = cart.nameofUser,
                proId = cart.proId,
                proImage = cart.proImage,
                proName = cart.proName,
                Quantity = cart.Quantity
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ReduceQuantity(CartDeleteViewModel model)
        {
            var cartItem = _cartService.GetByProID(model.proId);
            if (cartItem == null)
            {
                return NotFound();
            }
            if (cartItem.Quantity <= model.Quantity)
            {
                await _cartService.DeleteById(model.UserName);
                return RedirectToAction("Index");
            }
            else
            {
                var cart = _cartService.GetByUserName(model.UserName);
                cart.Quantity -= model.Quantity;
                await _cartService.UpdateAsSync(cart);
                return RedirectToAction("Index");
            }
        }
        [HttpGet]
        public IActionResult Delete(int id)
        {
            var cart = _cartService.GetByProID(id);
            if (cart == null)
            {
                return NotFound();
            }
            var model = new CartDeleteViewModel
            {
                proId = cart.proId,
                proImage = cart.proImage,
                proName = cart.proName,
                Quantity = cart.Quantity,
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(CartDeleteViewModel model)
        {
            var cartItem = _cartService.GetByProID(model.proId);
            if (cartItem == null)
            {
                return NotFound();
            }
            await _cartService.DeleteByProId(model.proId);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult DeleteAllYourCart(string id)
        {
            var cart = _cartService.GetByUserName(id);
            if (cart == null)
            {
                return RedirectToAction("Index");
            }
            var model = new CartDeleteViewModel
            {
                UserName = cart.nameofUser
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteAllYourCart()
        {
            await _cartService.DeleteAll();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult CreateOrder()
        {
            var model = new OrderCreateViewModel();           
            model.orderStatus = OrderStatus.InProgress;
            
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateOrder([FromForm]OrderCreateViewModel model)
        {
            var username = _userManager.GetUserName(User);
            var cart = _cartService.GetAll().ToList();
            if (username == null)
            {
                return NotFound();
            }
            foreach (Cart od in cart)
            {
                var product = _productService.GetById(od.proId);
                if (product.Quantity < od.Quantity)
                {
                    TempData["ErrorMessage"] = "[" + product.proName + "] quantity is not enough. Available quantity is: " + product.Quantity + ".";
                    return View();
                }
            }
            var order = new Order
            {
                UserName = username,
                orderTotal = 0,
                orderID = model.orderID,
                cusPhone = model.cusPhone,
                orderMessage = model.orderMessage,
                orderDateTime = model.orderDateTime,
                orderStatus = model.orderStatus,
                cusAddress = model.cusAddress,
                paymentMethod = model.paymentMethod,
            };
            var checkEmptyCart = _cartService.GetByUserName(username);
            if (checkEmptyCart == null)
            {
                return RedirectToAction("Order","Shop");
            }
            
            await _orderService.CreateAsSync(order);
            foreach (Cart od in cart) 
            {
                var orderDetail =new OrderDetail
                {

QuanLyBanHang/QuanLyBanHang/Controllers/CustomerController.cs
using System.Data;
using Microsoft.AspNetCore.Mvc;
using QuanLyBanHang.Entity;
using QuanLyBanHang.Models.Customer;
using QuanLyBanHang.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection.KeyManagement.Internal;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.AspNetCore.Identity;

namespace QuanLyBanHang.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CustomerController : Controller
    {
        private ICustomerService _customerService;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly SignInManager<IdentityUser> _signInManager;
        private IWebHostEnvironment _webHostEnvironment;
        public CustomerController(
            ICustomerService customerService,
            UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager,
            IWebHostEnvironment webHostEnvironment
            )
        {
            _customerService = customerService;
            _userManager = userManager;
            _signInManager = signInManager;
            _webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var model = _customerService.GetAll().Select(customer => new CustomerIndexViewModel
            {
                UserName = customer.nameofUser,
                cusPhone = customer.cusPhone,
                cusFullName = customer.cusFullName,
                cusEmail = customer.cusEmail,
                Gender = customer.cusGender,
            }).ToList();
            return View(model);
        }
        [HttpGet]
        public IActionResult Detail(string id)
        {

            var customer = _customerService.GetById(id);
            if (customer == null)
            {
                return NotFound();
            }
            var model = new CustomerDetailViewModel
            {
                UserName = customer.nameofUser,
                cusPhone = customer.cusPhone,
                cusFullName = customer.cusFullName,
                cusEmail = customer.cusEmail,
                Gender = customer.cusGender,
                cusAddress = customer.cusAddress,  
            };
            return View(model);
        }
        [HttpGet]
        public IActionResult Create()
        {
            var model = new CustomerCreateViewModel();
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerCreateViewModel model)
        {

            if (ModelState.IsValid)
            {
                var user = new IdentityUser()
                {
                    UserName = model.UserName,
                    Email = model.cusEmail
                };
                
                var result = await _userManager.CreateAsync(user, model.passWord);
                if (result.Succeeded)
                {
                    var customer = new Customer
                    {
                        nameofUser = model.UserName,
                        cusPhone = model.cusPhone,
                        cusFullName = model.cusFullName,
                        cusEmail = model.cusEmail,
                        cusGender = model.Gender,
                    };
                    await _customerService.CreateAsSync(customer);
                    return RedirectToAction("Index");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }
            return View(model);
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            var customer = _customerService.GetById(id);

            if (customer == null)
            {
                return NotFound();
            }
            var model = new CustomerDeleteViewModel();
            
            model.nameOfUser = customer.nameofUser;
            model.fullName = customer.cusFullName;

            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(CustomerDeleteViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(model.nameOfUser);
                if (user == null)
                {
                    return NotFound();
                }
                var result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    var customer = _customerService.GetById(model.nameOfUser);
                    if (customer == null)
                    {
                        return NotFound();
                    }
                    await _customerService.DeleteAsync(customer);
                    return RedirectToAction("Index");
                }
            }
            return View();
        }
    }
}

QuanLyBanHang/QuanLyBanHang/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>TK</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.css" />
    
</head>
<body class="sb-nav-fixed" style="background-color:white">    

    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">

        <a class="navbar-brand ps-3" style="text-align:center" asp-action="Index" asp-controller="Home">
            <img src="~/picture/logo.png" style="height:80px" />
        </a>
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
               
        <partial name="_LoginPartial" />
        
    </nav>
    @if (SignInManager.IsSignedIn(User))
    {
        <div id="layoutSidenav">
            <div id="layoutSidenav_nav">
                <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                    <div class="sb-sidenav-menu">
                        <div class="nav">
                            @if (User.IsInRole("Admin"))
                            {
                                <a class="nav-link" asp-action="Index" asp-controller="Home">
                                    <strong class="text-secondary">HOME</strong>
                                </a>
                                <a class="nav-link" asp-action="Index" asp-controller="Dashboard">
                                    <strong class="text-secondary">Dashboard</strong>
                                </a>
                            }else{
                                <a class="nav-link" asp-action="Index" asp-controller="Home">
                                    <strong class="text-secondary">HOME</strong>
                                </a>
                            }                            
                            <div class="sb-sidenav-menu-heading">User</div>
                            <a class="nav-link" asp-action="Index" asp-controller="Shop">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-border-all"></i></div>
                                All Products
                            </a>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseGender" aria-expanded="false" aria-controls="collapseGender">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-venus-mars"></i></div>
                                Gender
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseGender" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="SortedByMale" asp-controller="Shop">Male</a>
                                    <a class="nav-link" asp-action="SortedByFemale" asp-controller="Shop">Female</a>
                                </nav>
                            </div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProducer" aria-expanded="false" aria-controls="collapseProducer">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-hand-holding-dollar"></i></div>
                                Producers
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseProducer" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="SortedByNike" asp-controller="Shop">Nike</a>
                                    <a class="nav-link" asp-action="SortedByAdidas" asp-controller="Shop">Adidas</a>
                                </nav>
                            </div>
                            <a class="nav-link" asp-action="Index" asp-controller="Cart">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-cart-shopping"></i></div>
                                Your Cart
                            </a>
                            <a class="nav-link" asp-action="Order" asp-controller="Shop">
                                <div class="sb-nav-link-icon"><i class="fa-brands fa-shopify"></i></div>
                                Your Orders
                            </a>


                            <div class="sb-sidenav-menu-heading">Manager</div>
                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseProduct" aria-expanded="false" aria-controls="collapseProduct">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-store"></i></div>
                                Product
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseProduct" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="Index" asp-controller="Product">All Products</a>
                                    <a class="nav-link" asp-action="Create" asp-controller="Product">Add New Product</a>
                                </nav>
                            </div>

                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseCustomer" aria-expanded="false" aria-controls="collapseCustomer">
                                <div class="sb-nav-link-icon"><i class="fa-solid fa-users"></i></div>
                                Customer
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseCustomer" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="Index" asp-controller="Customer">All Customers</a>
                                    <a class="nav-link" asp-action="Create" asp-controller="Customer">Add New Customer</a>
                                </nav>
                            </div>

                            <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseOrder" aria-expanded="false" aria-controls="collapseOrder">
                                <div class="sb-nav-link-icon"><i class="fa-brands fa-shopify"></i></div>
                                Order
                                <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                            </a>
                            <div class="collapse" id="collapseOrder" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav">
                                    <a class="nav-link" asp-action="Index" asp-controller="Order">All Orders</a>
                                </nav>
                            </div>



                        </div>
                    </div>
                </nav>
            </div>
            <div id="layoutSidenav_content">
                
                    @RenderBody()
                
            </div>
        </div>
    }
    else
    {
        <div style="display:flex; justify-content:center; align-items:center; height:100%; background-image: linear-gradient(to top, gray, white)">
            @RenderBody()
        </div>
    }

    <script src="~/js/datatables-simple-demo.js"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>